[package]
name = "mmhyph"
description = "Hyphenation using precompiled memory-mapped tables"
version = "0.1.0"
authors = ["Jonathan Kew <jfkthame@gmail.com>"]
license = "MPL-2.0"

[dependencies]
memmap = "0.7.0"
arrayref = "0.3.5"

[dev-dependencies]
lazy_static = "1.2.0"
